---
- name: my first windows playbook
  hosts: windows1
  
  tasks:
  - name: my first windows tasks
    microsoft.ad.user:
      identity: bop1
      password: OnnumOnnumRendu112$
      state: present