---
- name: my first windows playbook
  hosts: windows1
  collections:
    - microsoft.ad.user
  tasks:
  - name: my first windows tasks
    microsoft.ad.user:
      identity: mayiru
      firstname: Bop
      lastname: smith
      company: cisco
      password: Welcome123$
      state: present

      