---
- name: my first windows playbook
  hosts: windows1
  tasks:
  - name: my first windows tasks
    ansible.windows.win_feature:
      name: Web-Server
      state: absent
  
  - name: Start SNMP TRAP
    ansible.windows.win_service:
      name: "SNMP TRAP"
      state: absent
  
  - name: copy file
    ansible.windows.win_copy:
      src: /etc/hosts
      dest: c:\ss.txt
  
  - name: whoami
    ansible.windows.win_whoami:

  - name: add user
    ansible.windows.win_user:
      name: bob
      state: absent
      
  - name: Get info for all installed services
    ansible.windows.win_service_info:
    register: service_info

  - name: print service info
    ansible.builtin.debug:
      var: service_info
